import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Erium Node',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
        {children}
        </Provider>
      </body>
    </html>
  )
}
