import './globals.css'
// import { Inter } from 'next/font/google'
import Provider from '@/SessionProvider'

// const inter = Inter({ subsets: ['latin'] })

// const inter = Inter({ subsets: ['latin'], display: 'swap', adjustFontFallback: false})



export const metadata = {
  title: 'Erium Node',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // className={inter.className}
  return (
    <html lang="en">
      <body >
      <Provider>
        {children}
        </Provider>
      </body>
    </html>
  )
}
